apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: userservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: alenguler/userservice
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    name: userservice
spec:
  type: ClusterIP    
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: userservice

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: userservice-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: userservice
  minReplicas: 3
  maxReplicas: 9
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 5